# Generated by Django 3.2.7 on 2021-09-21 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name': 'Membro', 'verbose_name_plural': 'Equipe'},
        ),
    ]
